# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timetable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timetable.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftimetable.proto\"\xc5\x03\n\x06Lesson\x12+\n\ractual_lesson\x18\x01 \x02(\x0b\x32\x14.Lesson.ActualLesson\x12 \n\x07teacher\x18\x02 \x02(\x0b\x32\x0f.Lesson.Teacher\x12\x1a\n\x04time\x18\x03 \x02(\x0b\x32\x0c.Lesson.Time\x12\x1c\n\x05place\x18\x04 \x02(\x0b\x32\r.Lesson.Place\x1a\x31\n\x0c\x41\x63tualLesson\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0blesson_type\x18\x02 \x02(\t\x1a\x44\n\x07Teacher\x12\x11\n\tlast_name\x18\x01 \x02(\t\x12\x12\n\nfirst_name\x18\x02 \x02(\t\x12\x12\n\npatronymic\x18\x03 \x02(\t\x1a\x90\x01\n\x04Time\x12\x0e\n\x06parity\x18\x01 \x02(\t\x12&\n\x05start\x18\x02 \x02(\x0b\x32\x17.Lesson.Time.ActualTime\x12$\n\x03\x65nd\x18\x03 \x02(\x0b\x32\x17.Lesson.Time.ActualTime\x1a*\n\nActualTime\x12\x0c\n\x04hour\x18\x01 \x02(\x05\x12\x0e\n\x06minute\x18\x02 \x02(\x05\x1a&\n\x05Place\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\t\x12\x0c\n\x04room\x18\x02 \x02(\t\"%\n\tTimeTable\x12\x18\n\x07lessons\x18\x04 \x03(\x0b\x32\x07.Lesson')
)




_LESSON_ACTUALLESSON = _descriptor.Descriptor(
  name='ActualLesson',
  full_name='Lesson.ActualLesson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Lesson.ActualLesson.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lesson_type', full_name='Lesson.ActualLesson.lesson_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=216,
)

_LESSON_TEACHER = _descriptor.Descriptor(
  name='Teacher',
  full_name='Lesson.Teacher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_name', full_name='Lesson.Teacher.last_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='Lesson.Teacher.first_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patronymic', full_name='Lesson.Teacher.patronymic', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=286,
)

_LESSON_TIME_ACTUALTIME = _descriptor.Descriptor(
  name='ActualTime',
  full_name='Lesson.Time.ActualTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hour', full_name='Lesson.Time.ActualTime.hour', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minute', full_name='Lesson.Time.ActualTime.minute', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=433,
)

_LESSON_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='Lesson.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parity', full_name='Lesson.Time.parity', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='Lesson.Time.start', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='Lesson.Time.end', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LESSON_TIME_ACTUALTIME, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=433,
)

_LESSON_PLACE = _descriptor.Descriptor(
  name='Place',
  full_name='Lesson.Place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Lesson.Place.address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room', full_name='Lesson.Place.room', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=473,
)

_LESSON = _descriptor.Descriptor(
  name='Lesson',
  full_name='Lesson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actual_lesson', full_name='Lesson.actual_lesson', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacher', full_name='Lesson.teacher', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Lesson.time', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='place', full_name='Lesson.place', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LESSON_ACTUALLESSON, _LESSON_TEACHER, _LESSON_TIME, _LESSON_PLACE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=473,
)


_TIMETABLE = _descriptor.Descriptor(
  name='TimeTable',
  full_name='TimeTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lessons', full_name='TimeTable.lessons', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=512,
)

_LESSON_ACTUALLESSON.containing_type = _LESSON
_LESSON_TEACHER.containing_type = _LESSON
_LESSON_TIME_ACTUALTIME.containing_type = _LESSON_TIME
_LESSON_TIME.fields_by_name['start'].message_type = _LESSON_TIME_ACTUALTIME
_LESSON_TIME.fields_by_name['end'].message_type = _LESSON_TIME_ACTUALTIME
_LESSON_TIME.containing_type = _LESSON
_LESSON_PLACE.containing_type = _LESSON
_LESSON.fields_by_name['actual_lesson'].message_type = _LESSON_ACTUALLESSON
_LESSON.fields_by_name['teacher'].message_type = _LESSON_TEACHER
_LESSON.fields_by_name['time'].message_type = _LESSON_TIME
_LESSON.fields_by_name['place'].message_type = _LESSON_PLACE
_TIMETABLE.fields_by_name['lessons'].message_type = _LESSON
DESCRIPTOR.message_types_by_name['Lesson'] = _LESSON
DESCRIPTOR.message_types_by_name['TimeTable'] = _TIMETABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lesson = _reflection.GeneratedProtocolMessageType('Lesson', (_message.Message,), {

  'ActualLesson' : _reflection.GeneratedProtocolMessageType('ActualLesson', (_message.Message,), {
    'DESCRIPTOR' : _LESSON_ACTUALLESSON,
    '__module__' : 'timetable_pb2'
    # @@protoc_insertion_point(class_scope:Lesson.ActualLesson)
    })
  ,

  'Teacher' : _reflection.GeneratedProtocolMessageType('Teacher', (_message.Message,), {
    'DESCRIPTOR' : _LESSON_TEACHER,
    '__module__' : 'timetable_pb2'
    # @@protoc_insertion_point(class_scope:Lesson.Teacher)
    })
  ,

  'Time' : _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {

    'ActualTime' : _reflection.GeneratedProtocolMessageType('ActualTime', (_message.Message,), {
      'DESCRIPTOR' : _LESSON_TIME_ACTUALTIME,
      '__module__' : 'timetable_pb2'
      # @@protoc_insertion_point(class_scope:Lesson.Time.ActualTime)
      })
    ,
    'DESCRIPTOR' : _LESSON_TIME,
    '__module__' : 'timetable_pb2'
    # @@protoc_insertion_point(class_scope:Lesson.Time)
    })
  ,

  'Place' : _reflection.GeneratedProtocolMessageType('Place', (_message.Message,), {
    'DESCRIPTOR' : _LESSON_PLACE,
    '__module__' : 'timetable_pb2'
    # @@protoc_insertion_point(class_scope:Lesson.Place)
    })
  ,
  'DESCRIPTOR' : _LESSON,
  '__module__' : 'timetable_pb2'
  # @@protoc_insertion_point(class_scope:Lesson)
  })
_sym_db.RegisterMessage(Lesson)
_sym_db.RegisterMessage(Lesson.ActualLesson)
_sym_db.RegisterMessage(Lesson.Teacher)
_sym_db.RegisterMessage(Lesson.Time)
_sym_db.RegisterMessage(Lesson.Time.ActualTime)
_sym_db.RegisterMessage(Lesson.Place)

TimeTable = _reflection.GeneratedProtocolMessageType('TimeTable', (_message.Message,), {
  'DESCRIPTOR' : _TIMETABLE,
  '__module__' : 'timetable_pb2'
  # @@protoc_insertion_point(class_scope:TimeTable)
  })
_sym_db.RegisterMessage(TimeTable)


# @@protoc_insertion_point(module_scope)
