# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slava_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slava_proto.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11slava_proto.proto\"\xe0\x01\n\tDayOfWeek\x12\x0c\n\x04name\x18\x01 \x02(\t\x12%\n\x08schedule\x18\x02 \x02(\x0b\x32\x13.DayOfWeek.Schedule\x1a\x9d\x01\n\x08Schedule\x12+\n\x07lessons\x18\x01 \x03(\x0b\x32\x1a.DayOfWeek.Schedule.Lesson\x1a\x64\n\x06Lesson\x12\x0c\n\x04time\x18\x01 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\x11\n\tclassroom\x18\x03 \x01(\t\x12\x17\n\x0fname_of_subject\x18\x04 \x02(\t\x12\x0f\n\x07teacher\x18\x05 \x01(\t')
)




_DAYOFWEEK_SCHEDULE_LESSON = _descriptor.Descriptor(
  name='Lesson',
  full_name='DayOfWeek.Schedule.Lesson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='DayOfWeek.Schedule.Lesson.time', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='DayOfWeek.Schedule.Lesson.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classroom', full_name='DayOfWeek.Schedule.Lesson.classroom', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name_of_subject', full_name='DayOfWeek.Schedule.Lesson.name_of_subject', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacher', full_name='DayOfWeek.Schedule.Lesson.teacher', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=246,
)

_DAYOFWEEK_SCHEDULE = _descriptor.Descriptor(
  name='Schedule',
  full_name='DayOfWeek.Schedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lessons', full_name='DayOfWeek.Schedule.lessons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DAYOFWEEK_SCHEDULE_LESSON, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=246,
)

_DAYOFWEEK = _descriptor.Descriptor(
  name='DayOfWeek',
  full_name='DayOfWeek',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DayOfWeek.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='DayOfWeek.schedule', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DAYOFWEEK_SCHEDULE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=246,
)

_DAYOFWEEK_SCHEDULE_LESSON.containing_type = _DAYOFWEEK_SCHEDULE
_DAYOFWEEK_SCHEDULE.fields_by_name['lessons'].message_type = _DAYOFWEEK_SCHEDULE_LESSON
_DAYOFWEEK_SCHEDULE.containing_type = _DAYOFWEEK
_DAYOFWEEK.fields_by_name['schedule'].message_type = _DAYOFWEEK_SCHEDULE
DESCRIPTOR.message_types_by_name['DayOfWeek'] = _DAYOFWEEK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DayOfWeek = _reflection.GeneratedProtocolMessageType('DayOfWeek', (_message.Message,), {

  'Schedule' : _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {

    'Lesson' : _reflection.GeneratedProtocolMessageType('Lesson', (_message.Message,), {
      'DESCRIPTOR' : _DAYOFWEEK_SCHEDULE_LESSON,
      '__module__' : 'slava_proto_pb2'
      # @@protoc_insertion_point(class_scope:DayOfWeek.Schedule.Lesson)
      })
    ,
    'DESCRIPTOR' : _DAYOFWEEK_SCHEDULE,
    '__module__' : 'slava_proto_pb2'
    # @@protoc_insertion_point(class_scope:DayOfWeek.Schedule)
    })
  ,
  'DESCRIPTOR' : _DAYOFWEEK,
  '__module__' : 'slava_proto_pb2'
  # @@protoc_insertion_point(class_scope:DayOfWeek)
  })
_sym_db.RegisterMessage(DayOfWeek)
_sym_db.RegisterMessage(DayOfWeek.Schedule)
_sym_db.RegisterMessage(DayOfWeek.Schedule.Lesson)


# @@protoc_insertion_point(module_scope)
