# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schedule.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eschedule.proto\"\x81\x01\n\x08Schedule\x12!\n\x07lessons\x18\x01 \x03(\x0b\x32\x10.Schedule.Lesson\x1aR\n\x06Lesson\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07teacher\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x02(\t\x12\r\n\x05place\x18\x04 \x02(\t\x12\x0c\n\x04room\x18\x05 \x01(\t')
)




_SCHEDULE_LESSON = _descriptor.Descriptor(
  name='Lesson',
  full_name='Schedule.Lesson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Schedule.Lesson.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacher', full_name='Schedule.Lesson.teacher', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Schedule.Lesson.time', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='place', full_name='Schedule.Lesson.place', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room', full_name='Schedule.Lesson.room', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=148,
)

_SCHEDULE = _descriptor.Descriptor(
  name='Schedule',
  full_name='Schedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lessons', full_name='Schedule.lessons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCHEDULE_LESSON, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=148,
)

_SCHEDULE_LESSON.containing_type = _SCHEDULE
_SCHEDULE.fields_by_name['lessons'].message_type = _SCHEDULE_LESSON
DESCRIPTOR.message_types_by_name['Schedule'] = _SCHEDULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {

  'Lesson' : _reflection.GeneratedProtocolMessageType('Lesson', (_message.Message,), {
    'DESCRIPTOR' : _SCHEDULE_LESSON,
    '__module__' : 'schedule_pb2'
    # @@protoc_insertion_point(class_scope:Schedule.Lesson)
    })
  ,
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)
_sym_db.RegisterMessage(Schedule.Lesson)


# @@protoc_insertion_point(module_scope)
